dbt-labs/corp

msa.md
@drewbanin @cmcarthur please review. several small changes to the MSA:
- Simplify the IP assignment process. There is no such thing as a "preliminary work" in this version--once the client accepts the work we have delivered, IP ownership is immediately transferred. This creates a payment obligation at the same time.
- Other minor clean-ups.
=> several MSA updates

msa.md
@cmcarthur @drewbanin 
LMK if either of you have a problem with adding this. Ryan has reviewed it and given it his blessing.
=> add security section to msa

Writing bug reports in analytics.md
@eogilvy12 – let me know if this isn't the right place for this
=> Add bug report guide

git-guide.md
* Changed the structure so each section read more consistently
* Ensured each line was <80 chars
* Made small changes to the content
=> Update git guide

dbt_coding_conventions.md
@jtcohen6 – I'm simultaneously working on:
* A Discourse article: how we structure our dbt projects
* Updating [the best practice](https://docs.getdbt.com/docs/best-practices) docs
* Thinking about dbt-init things.
As a result of this, I felt there were some required updates to our coding conventions. I also don't want to overlap with your open PR too much, so this is just a WIP, but would love your feedback.
=> Update coding conventions

handbook.md
This PR adds the verbatim copy of the existing handbook to the corp repo. I have a change related to credit card policies that I'd like to add to the handbook, and I wanted to get it into a place where we could more easily make changes to this doc and keep those changes transparent for anyone on the team to see. I think that this is such an important document that we should git it.
PLMK if either of you disagree with this at all and we can circle up and discuss.
=> added existing handbook to corp repo

handbook.md
Take a look and let me know what you think. It almost feels silly to have to say the final point, but I do want to make sure that we're super-clear with people that this is a big deal, and that it's one of the few areas where not adhering to corporate policies actually is a crime (embezzlement, theft).
Also: anything missing?
=> handbook expense policies

handbook.md
*very* inspired from https://about.gitlab.com/handbook/people-group/code-of-conduct/#background-checks (they did a great job)
the only things that are different are their references to "candidate experience specialists"—we don't have those yet.
=> background check information in the handbook

values.md
I strongly disagree that we are exceptional people. I think what makes a company great is that it creates an environment where otherwise normal people can do exceptional work. We all have things that make us unique, but we're not all that exceptional. What is remarkable, is that together, we're able to create something that is actually quite exceptional.
=> Updated "We are humble"

mission.md
FYI, I'm recording this here for posterity. This is not current at the time that this PR is being submitted and will be superseded with another PR shortly.
=> original mission statement (from 2018 fall retreat)

mission.md
This PR updates the prior version of the mission to our current mission (as announced at the fall retreat of 2019).
=> updated mission from 2019 fall retreat

values.md
These are long overdue; this is primarily from work I did around values updates for the retreat last year. Please let me know if you have any comments on the wording (or, I suppose, intent if applicable)...I spent a lot of time trying to get this right but your eyes are very much appreciated.
=> values update q2 2020

looker_style_guide.md
As we grow the Data team, we need to think about adding guidelines/coding conventions to our Looker project.
This Style Guide breaks down coding conventions by:
- the structure our a LookML project
- Views: dimensions, measures
- Explores: categorization, joins
=> feat: LookML Style Guide

looker_style_guide.md
Adding Tristan's article as a reference for folks to understand what goes in dbt vs Looker from the get-go
=> feat: add resource references

looker_style_guide.md
ref: [user attribute for prod dbt schema](https://github.com/fishtown-analytics/looker/commit/1ba7af4ec4e1da9f3b9d9ea512c504f0359bea9b)
Adding this requirement to our Looker Style Guide and also adding explore descriptions as a requirement
=> add prod_dbt_schema requirement

looker_style_guide.md
Made a couple minor changes that better reflect how we implement this style guide
=> clarified the style guide for better consistency

mission.md
Open to suggestion here, maybe "data professionals" - but got some feedback that "data analyst" doesn't capture all of the people that use dbt, so it may be time for a refresh!
=> Update Mission Statement

dbt_style_guide.md
We have changed the following attributes for metrics:
- type->calculation_method
- sql->expression
- type: expression -> calculation_method: derived
=> Update: Rename metrics attributes

handbook.md
Edits per Legal's request:
Deleted all of the Workplace Commitments: (1) EOE, (2) Non-Harassment / Non-Discrimination Policy, (3) Complaint Procedure, (4) Open Door Policy, (5) Breach of Workplace Commitments
*Deleted the following Company Policies and Procedures: (1) Trust and Flexibility, (2) Code of Professional Conduct) and replaced with: “Code of Conduct Follow the guide for behavior described in the dbt labs Code of Conduct."
Additional edits:
3. Removed from Dress Code: "If you wouldn't wear it in front of your grandmother, please don't wear it to work!"
4. Edited in Time Off: "Avoid abusing the policy by taking time off at certain times that can impact their job and productivity"
=> Merge recent handbook edits into main

dbt_style_guide.md
Emphasize use of configurations prefixed in `+` in `dbt_project.yml` to avoid issues with directory names.
=> Add dbt_project.yml configuration style
